/**
 * Environment configuration for Web3Lancer
 * 
 * This module provides centralized access to environment variables
 * and configuration settings across the application.
 */

/**
 * API Endpoints configuration
 */
export const API_ENDPOINTS = {
  // PhotonLancerr Payment API
  PAYMENT: {
    BASE_URL: process.env.NEXT_PUBLIC_PAYMENT_API_URL, // Relies on environment variable
    HEALTH: '/health',
    PAYMENTS: '/payments',
    PLUGINS: '/plugins',
  },
  
  // Appwrite endpoints are handled through the Appwrite client, 
  // which itself should be configured using environment variables (see api.ts)
};

/**
 * Appwrite configuration
 * These IDs must be set in your environment variables.
 */
export const APPWRITE_CONFIG = {
  // ENDPOINT and PROJECT are typically configured directly in the Appwrite client initialization (see src/utils/api.ts)
  // However, if needed elsewhere, they can be defined here from env vars:
  // ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT,
  // PROJECT: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
  
  DATABASES: {
    USERS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_USERS_ID,
    BOOKMARKS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_BOOKMARKS_ID,
    PROJECTS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PROJECTS_ID,
    MESSAGES: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_MESSAGES_ID,
    TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_TRANSACTIONS_ID,
    NOTIFICATIONS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_NOTIFICATIONS_ID,
    JOBS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID,
    WALLET: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_WALLET_ID,
    PAYMENT_METHODS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PAYMENTMETHODS_ID
  },
  COLLECTIONS: {
    PROFILES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILES_ID,
    CONNECTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONNECTIONS_ID,
    BOOKMARKS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_BOOKMARKS_ID,
    CATEGORIES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CATEGORIES_ID,
    PROJECTS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROJECTS_ID,
    TASKS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_TASKS_ID,
    MESSAGES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_MESSAGES_ID,
    TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_TRANSACTIONS_ID,
    NOTIFICATIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_NOTIFICATIONS_ID,
    APPLICATIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APPLICATIONS_ID,
    REVIEWS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_REVIEWS_ID,
    JOBS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOBS_ID,
    WALLETS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_WALLETS_ID,
    BALANCES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_BALANCES_ID,
    CRYPTO_TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CRYPTOTRANSACTIONS_ID,
    PAYMENT_METHODS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PAYMENTMETHODS_ID
  },
  STORAGE: {
    // The main profile picture bucket ID is often referred to as NEXT_PUBLIC_APPWRITE_BUCKET_ID
    PROFILE_PICTURES: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID, 
    JOB_ATTACHMENTS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_JOB_ATTACHMENTS_ID,
    PROJECT_DOCUMENTS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_DOCUMENTS_ID,
    PROJECT_MEDIA: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_MEDIA_ID,
    MESSAGE_ATTACHMENTS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_MESSAGE_ATTACHMENTS_ID,
    MISCELLANEOUS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_MISCELLANEOUS_ID
  }
};

// New schema database IDs
export const PROFILES_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PROFILES_ID!;
export const JOBS_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID!;
export const FINANCE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_FINANCE_ID!;
export const SOCIAL_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_SOCIAL_ID!;
export const CONTENT_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CONTENT_ID!;
export const GOVERNANCE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_GOVERNANCE_ID!;
export const ACTIVITY_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ACTIVITY_ID!;
export const CORE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CORE_ID!;

// ProfilesDB Collection IDs
export const USER_PROFILES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PROFILES_ID!;
export const PROFILE_VERIFICATIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILE_VERIFICATIONS_ID!;

// JobsDB Collection IDs
export const JOB_POSTINGS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_POSTINGS_ID!;
export const JOB_PROPOSALS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_PROPOSALS_ID!;
export const JOB_CONTRACTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_CONTRACTS_ID!;
export const CONTRACT_MILESTONES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_MILESTONES_ID!;
export const USER_REVIEWS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_REVIEWS_ID!;

// FinanceDB Collection IDs
export const USER_WALLETS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_WALLETS_ID!;
export const PLATFORM_TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_TRANSACTIONS_ID!;
export const USER_PAYMENT_METHODS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PAYMENT_METHODS_ID!;
export const ESCROW_TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ESCROW_TRANSACTIONS_ID!;

// SocialDB Collection IDs
export const USER_CONNECTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_CONNECTIONS_ID!;
export const DIRECT_MESSAGES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_DIRECT_MESSAGES_ID!;
export const GROUP_CHATS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHATS_ID!;
export const GROUP_CHAT_MESSAGES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHAT_MESSAGES_ID!;

// ContentDB Collection IDs
export const USER_POSTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_POSTS_ID!;
export const POST_INTERACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_POST_INTERACTIONS_ID!;
export const USER_PORTFOLIOS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PORTFOLIOS_ID!;
export const USER_ARTICLES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_ARTICLES_ID!;
export const USER_BOOKMARKS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_BOOKMARKS_ID!;

// GovernanceDB Collection IDs
export const CONTRACT_DISPUTES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_DISPUTES_ID!;
export const DISPUTE_VOTES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_DISPUTE_VOTES_ID!;
export const PLATFORM_PROPOSALS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_PROPOSALS_ID!;

// ActivityDB Collection IDs
export const USER_NOTIFICATIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_NOTIFICATIONS_ID!;
export const AUDIT_LOGS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_AUDIT_LOGS_ID!;

// CoreDB Collection IDs
export const APP_SKILLS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APP_SKILLS_ID!;
export const APP_CATEGORIES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APP_CATEGORIES_ID!;
export const PLATFORM_SETTINGS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_SETTINGS_ID!;

// New schema bucket IDs
export const PROFILE_AVATARS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROFILE_AVATARS_ID!;
export const COVER_IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_COVER_IMAGES_ID!;
export const VERIFICATION_DOCUMENTS_PRIVATE_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_VERIFICATION_DOCUMENTS_PRIVATE_ID!;

/**
 * Environment settings
 */
export const ENV = {
  IS_PRODUCTION: process.env.NODE_ENV === 'production',
  IS_DEVELOPMENT: process.env.NODE_ENV === 'development',
};

/**
 * Application configuration
 */
export const APP_CONFIG = {
  APP_URL: process.env.NEXT_PUBLIC_APP_URL
};

// Appwrite Project
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID || '';
export const ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT || '';

// Databases
export const PROFILES_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_PROFILES_DATABASE_ID || '';
export const PROJECT_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_DATABASE_ID || '';
export const MESSAGES_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_MESSAGES_DATABASE_ID || '';
export const TRANSACTIONS_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_TRANSACTIONS_DATABASE_ID || '';

// Collections
export const USER_PROFILES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_USER_PROFILES_COLLECTION_ID || '';
export const PROJECTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID || '';
export const PROPOSALS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PROPOSALS_COLLECTION_ID || '';
export const REVIEWS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_REVIEWS_COLLECTION_ID || '';
export const MESSAGES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_MESSAGES_COLLECTION_ID || '';
export const CHANNELS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_CHANNELS_COLLECTION_ID || '';
export const TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_TRANSACTIONS_COLLECTION_ID || '';
export const NOTIFICATION_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_NOTIFICATION_COLLECTION_ID || '';
export const VERIFICATION_REQUESTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_VERIFICATION_REQUESTS_COLLECTION_ID || '';

// Storage Buckets
export const PROFILE_AVATARS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_PROFILE_AVATARS_BUCKET_ID || '';
export const COVER_IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_COVER_IMAGES_BUCKET_ID || '';
export const PROJECT_ATTACHMENTS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ATTACHMENTS_BUCKET_ID || '';
export const PROPOSAL_ATTACHMENTS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_PROPOSAL_ATTACHMENTS_BUCKET_ID || '';
export const MESSAGE_ATTACHMENTS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_MESSAGE_ATTACHMENTS_BUCKET_ID || '';
export const VERIFICATION_DOCUMENTS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_VERIFICATION_DOCUMENTS_BUCKET_ID || '';

// API Routes
export const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT || '';

// Web3 Configuration
export const CHAIN_ID = process.env.NEXT_PUBLIC_CHAIN_ID || '1';
export const ESCROW_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_ESCROW_CONTRACT_ADDRESS || '';
export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL || '';

// App Configuration
export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || 'Web3Lancer';
export const APP_DESCRIPTION = process.env.NEXT_PUBLIC_APP_DESCRIPTION || 'Decentralized freelancing platform';
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://web3lancer.app';

// Appwrite Project Config
export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT || 'https://cloud.appwrite.io/v1';
export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID || '';

// Database IDs
export const PROFILE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PROFILES_ID || 'profiles';
export const PROJECT_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID || 'jobs';
export const FINANCE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_FINANCE_ID || 'finance';
export const SOCIAL_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_SOCIAL_ID || 'social';
export const CONTENT_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CONTENT_ID || 'content';

// Collection IDs
export const PROFILES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PROFILES_ID || 'user_profiles';
export const VERIFICATION_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILE_VERIFICATIONS_ID || 'profile_verifications';
export const PROJECTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_POSTINGS_ID || 'job_postings';
export const PROPOSALS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_PROPOSALS_ID || 'job_proposals';
export const JOB_CONTRACTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_CONTRACTS_ID || 'job_contracts';
export const CONTRACT_MILESTONES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_MILESTONES_ID || 'contract_milestones';
export const USER_REVIEWS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_REVIEWS_ID || 'user_reviews';

// Storage Bucket IDs
export const PROFILE_AVATARS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROFILE_AVATARS_ID || 'profile_avatars';
export const PROFILE_COVERS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_COVER_IMAGES_ID || 'profile_covers';
export const VERIFICATION_DOCUMENTS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_VERIFICATION_DOCUMENTS_PRIVATE_ID || 'verification_documents';
export const PROJECT_ATTACHMENTS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_JOB_ATTACHMENTS_ID || 'job_attachments';

// Skills list for form selections
export const AVAILABLE_SKILLS = [
  'React', 'JavaScript', 'TypeScript', 'Node.js', 'Python', 
  'Solidity', 'Web3', 'Smart Contracts', 'Blockchain',
  'UI/UX', 'Design', 'Backend', 'Frontend', 'Full Stack',
  'AWS', 'Cloud', 'Database', 'Rust', 'Go', 'DevOps'
];

// Project categories
export const PROJECT_CATEGORIES = [
  'Development', 'Design', 'Marketing', 'Writing', 'Admin Support',
  'Blockchain', 'Smart Contracts', 'NFT', 'DeFi', 'DAO', 'Metaverse'
];

// API routes
export const API_ROUTES = {
  PROFILE: '/api/profile',
  PROJECT: '/api/project',
  PROPOSAL: '/api/proposal',
  CONTRACT: '/api/contract',
  REVIEW: '/api/review',
  AUTH: '/api/auth',
};

// Environment constants for financial system
export const FINANCE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_FINANCE_ID || 'finance_db';
export const USER_WALLETS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_WALLETS_ID || 'user_wallets';
export const PLATFORM_TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_TRANSACTIONS_ID || 'platform_transactions';
export const USER_PAYMENT_METHODS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PAYMENT_METHODS_ID || 'user_payment_methods';
export const ESCROW_TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ESCROW_TRANSACTIONS_ID || 'escrow_transactions';

// New environment variables
export const NEXT_PUBLIC_APP_URL = process.env.NEXT_PUBLIC_APP_URL || '';
export const NEXT_PUBLIC_APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT || '';
export const NEXT_PUBLIC_APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID || '';

// Database IDs
export const NEXT_PUBLIC_APPWRITE_DATABASE_PROFILES_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PROFILES_ID || '';
export const NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID || '';
export const NEXT_PUBLIC_APPWRITE_DATABASE_FINANCE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_FINANCE_ID || '';
export const NEXT_PUBLIC_APPWRITE_DATABASE_SOCIAL_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_SOCIAL_ID || '';
export const NEXT_PUBLIC_APPWRITE_DATABASE_CONTENT_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CONTENT_ID || '';
export const NEXT_PUBLIC_APPWRITE_DATABASE_GOVERNANCE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_GOVERNANCE_ID || '';
export const NEXT_PUBLIC_APPWRITE_DATABASE_ACTIVITY_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ACTIVITY_ID || '';
export const NEXT_PUBLIC_APPWRITE_DATABASE_CORE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CORE_ID || '';

// Collection IDs - ProfilesDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PROFILES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PROFILES_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILE_VERIFICATIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILE_VERIFICATIONS_ID || '';

// Collection IDs - JobsDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_POSTINGS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_POSTINGS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_PROPOSALS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_PROPOSALS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_CONTRACTS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_CONTRACTS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_MILESTONES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_MILESTONES_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_REVIEWS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_REVIEWS_ID || '';

// Collection IDs - FinanceDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_WALLETS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_WALLETS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_TRANSACTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_TRANSACTIONS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PAYMENT_METHODS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PAYMENT_METHODS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_ESCROW_TRANSACTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ESCROW_TRANSACTIONS_ID || '';

// Collection IDs - SocialDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_CONNECTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_CONNECTIONS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_DIRECT_MESSAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_DIRECT_MESSAGES_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHATS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHATS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHAT_MESSAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHAT_MESSAGES_ID || '';

// Collection IDs - ContentDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_POSTS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_POSTS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_POST_INTERACTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_POST_INTERACTIONS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PORTFOLIOS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PORTFOLIOS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_ARTICLES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_ARTICLES_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_BOOKMARKS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_BOOKMARKS_ID || '';

// Collection IDs - GovernanceDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_DISPUTES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_DISPUTES_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_DISPUTE_VOTES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_DISPUTE_VOTES_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_PROPOSALS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_PROPOSALS_ID || '';

// Collection IDs - ActivityDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_USER_NOTIFICATIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_NOTIFICATIONS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_AUDIT_LOGS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_AUDIT_LOGS_ID || '';

// Collection IDs - CoreDB
export const NEXT_PUBLIC_APPWRITE_COLLECTION_APP_SKILLS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APP_SKILLS_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_APP_CATEGORIES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APP_CATEGORIES_ID || '';
export const NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_SETTINGS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_SETTINGS_ID || '';

// Storage Bucket IDs
export const NEXT_PUBLIC_APPWRITE_BUCKET_PROFILE_AVATARS_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROFILE_AVATARS_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_COVER_IMAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_COVER_IMAGES_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_VERIFICATION_DOCUMENTS_PRIVATE_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_VERIFICATION_DOCUMENTS_PRIVATE_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_POST_MEDIA_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_POST_MEDIA_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_MESSAGE_ATTACHMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_MESSAGE_ATTACHMENTS_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_MEDIA_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_MEDIA_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_DOCUMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_DOCUMENTS_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_JOB_ATTACHMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_JOB_ATTACHMENTS_ID || '';
export const NEXT_PUBLIC_APPWRITE_BUCKET_MISCELLANEOUS_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_MISCELLANEOUS_ID || '';
