/**
 * Environment configuration for Web3Lancer
 * 
 * This module provides centralized access to environment variables
 * and configuration settings across the application.
 */

/**
 * API Endpoints configuration
 */
export const API_ENDPOINTS = {
  // PhotonLancerr Payment API
  PAYMENT: {
    BASE_URL: process.env.NEXT_PUBLIC_PAYMENT_API_URL, // Relies on environment variable
    HEALTH: '/health',
    PAYMENTS: '/payments',
    PLUGINS: '/plugins',
  },
  
  // Appwrite endpoints are handled through the Appwrite client, 
  // which itself should be configured using environment variables (see api.ts)
};

/**
 * Appwrite configuration
 * These IDs must be set in your environment variables.
 */
export const APPWRITE_CONFIG = {
  // ENDPOINT and PROJECT are typically configured directly in the Appwrite client initialization (see src/utils/api.ts)
  // However, if needed elsewhere, they can be defined here from env vars:
  // ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT,
  // PROJECT: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
  
  DATABASES: {
    USERS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_USERS_ID,
    BOOKMARKS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_BOOKMARKS_ID,
    PROJECTS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PROJECTS_ID,
    MESSAGES: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_MESSAGES_ID,
    TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_TRANSACTIONS_ID,
    NOTIFICATIONS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_NOTIFICATIONS_ID,
    JOBS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID,
    WALLET: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_WALLET_ID,
    PAYMENT_METHODS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PAYMENTMETHODS_ID
  },
  COLLECTIONS: {
    PROFILES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILES_ID,
    CONNECTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONNECTIONS_ID,
    BOOKMARKS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_BOOKMARKS_ID,
    CATEGORIES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CATEGORIES_ID,
    PROJECTS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROJECTS_ID,
    TASKS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_TASKS_ID,
    MESSAGES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_MESSAGES_ID,
    TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_TRANSACTIONS_ID,
    NOTIFICATIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_NOTIFICATIONS_ID,
    APPLICATIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APPLICATIONS_ID,
    REVIEWS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_REVIEWS_ID,
    JOBS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOBS_ID,
    WALLETS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_WALLETS_ID,
    BALANCES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_BALANCES_ID,
    CRYPTO_TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CRYPTOTRANSACTIONS_ID,
    PAYMENT_METHODS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PAYMENTMETHODS_ID
  },
  STORAGE: {
    // The main profile picture bucket ID is often referred to as NEXT_PUBLIC_APPWRITE_BUCKET_ID
    PROFILE_PICTURES: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID, 
    JOB_ATTACHMENTS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_JOB_ATTACHMENTS_ID,
    PROJECT_DOCUMENTS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_DOCUMENTS_ID,
    PROJECT_MEDIA: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_MEDIA_ID,
    MESSAGE_ATTACHMENTS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_MESSAGE_ATTACHMENTS_ID,
    MISCELLANEOUS: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_MISCELLANEOUS_ID
  }
};

// New schema database IDs
export const PROFILES_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_PROFILES_ID!;
export const JOBS_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID!;
export const FINANCE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_FINANCE_ID!;
export const SOCIAL_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_SOCIAL_ID!;
export const CONTENT_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CONTENT_ID!;
export const GOVERNANCE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_GOVERNANCE_ID!;
export const ACTIVITY_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ACTIVITY_ID!;
export const CORE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CORE_ID!;

// ProfilesDB Collection IDs
export const USER_PROFILES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PROFILES_ID!;
export const PROFILE_VERIFICATIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILE_VERIFICATIONS_ID!;

// JobsDB Collection IDs
export const JOB_POSTINGS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_POSTINGS_ID!;
export const JOB_PROPOSALS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_PROPOSALS_ID!;
export const JOB_CONTRACTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_JOB_CONTRACTS_ID!;
export const CONTRACT_MILESTONES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_MILESTONES_ID!;
export const USER_REVIEWS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_REVIEWS_ID!;

// FinanceDB Collection IDs
export const USER_WALLETS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_WALLETS_ID!;
export const PLATFORM_TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_TRANSACTIONS_ID!;
export const USER_PAYMENT_METHODS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PAYMENT_METHODS_ID!;
export const ESCROW_TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ESCROW_TRANSACTIONS_ID!;

// SocialDB Collection IDs
export const USER_CONNECTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_CONNECTIONS_ID!;
export const DIRECT_MESSAGES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_DIRECT_MESSAGES_ID!;
export const GROUP_CHATS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHATS_ID!;
export const GROUP_CHAT_MESSAGES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_GROUP_CHAT_MESSAGES_ID!;

// ContentDB Collection IDs
export const USER_POSTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_POSTS_ID!;
export const POST_INTERACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_POST_INTERACTIONS_ID!;
export const USER_PORTFOLIOS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PORTFOLIOS_ID!;
export const USER_ARTICLES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_ARTICLES_ID!;
export const USER_BOOKMARKS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_BOOKMARKS_ID!;

// GovernanceDB Collection IDs
export const CONTRACT_DISPUTES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CONTRACT_DISPUTES_ID!;
export const DISPUTE_VOTES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_DISPUTE_VOTES_ID!;
export const PLATFORM_PROPOSALS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_PROPOSALS_ID!;

// ActivityDB Collection IDs
export const USER_NOTIFICATIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_NOTIFICATIONS_ID!;
export const AUDIT_LOGS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_AUDIT_LOGS_ID!;

// CoreDB Collection IDs
export const APP_SKILLS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APP_SKILLS_ID!;
export const APP_CATEGORIES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_APP_CATEGORIES_ID!;
export const PLATFORM_SETTINGS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PLATFORM_SETTINGS_ID!;

// New schema bucket IDs
export const PROFILE_AVATARS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_PROFILE_AVATARS_ID!;
export const COVER_IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_COVER_IMAGES_ID!;
export const VERIFICATION_DOCUMENTS_PRIVATE_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_VERIFICATION_DOCUMENTS_PRIVATE_ID!;

/**
 * Environment settings
 */
export const ENV = {
  IS_PRODUCTION: process.env.NODE_ENV === 'production',
  IS_DEVELOPMENT: process.env.NODE_ENV === 'development',
};

/**
 * Application configuration
 */
export const APP_CONFIG = {
  APP_URL: process.env.NEXT_PUBLIC_APP_URL
};
