

















}  }    );      ),        child: Text('Hello Web3Lancer!'),      body: const Center(      drawer: Sidebar(),      appBar: Header(),    return Scaffold(  Widget build(BuildContext context) {  @override  const HomeScreen({Key? key}) : super(key: key);class HomeScreen extends StatelessWidget {import '../widgets/sidebar.dart';import '../widgets/header.dart';import 'package:flutter/material.dart';