













































}  }    );      ),        ],          ),            },              Navigator.pop(context);            onTap: () {            title: const Text('Calendar'),          ListTile(          ),            },              Navigator.pop(context);            onTap: () {            title: const Text('Planning'),          ListTile(          ),            },              Navigator.pop(context);            onTap: () {            title: const Text('Projects'),          ListTile(          ),            },              Navigator.pop(context);            onTap: () {            title: const Text('Dashboard'),          ListTile(          ),            child: Text('Web3Lancer'),            ),              color: Colors.blue,            decoration: BoxDecoration(          const DrawerHeader(        children: <Widget>[        padding: EdgeInsets.zero,      child: ListView(    return Drawer(  Widget build(BuildContext context) {  @override  const Sidebar({Key? key}) : super(key: key);class Sidebar extends StatelessWidget {import 'package:flutter/material.dart';